### ISSUE TITLE
Cannot recover after PGBouncer restarts

### ISSUE THREAD

**Issue by fridex** [fabric8-analytics/fabric8-analytics-jobs#105]
If PGBouncer gets restarted, it looks like jobs cannot recover connection with the following error:

```
[pid: 1|app: 0|req: 5342/5342] 10.129.4.1 () {52 vars in 1262 bytes} [Thu Jul 20 08:47:17 2017] POST /api/v1/jobs/selective-flow-scheduling?state=running => generated 1621 bytes in 78 msecs (HTTP/1.1 201) 2 headers in 78 bytes (1 switches on core 0)
ERROR:root:Job 'None' failed, registering ErrorHandler: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT DISTINCT "packages"."name" AS "name", "ecosystems"."name" AS "ecosystem", "versions"."identifier" AS "version" FROM "worker_results" INNER JOIN "analyses" ON "worker_results"."analysis_id" = "analyses"."id" INNER JOIN "versions" ON "analyses"."version_id" = "versions"."id" INNER JOIN "packages" ON "versions"."package_id" = "packages"."id" INNER JOIN "ecosystems" ON "ecosystems"."id" = "packages"."ecosystem_id" WHERE "worker_results"."error" = FALSE AND "worker_results"."worker" = \'InitAnalysisFlow\''] [parameters: [{}]]
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1112, in _execute_context
    conn = self.__connection
AttributeError: 'Connection' object has no attribute '_Connection__connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1114, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.InvalidRequestError: Can't reconnect until invalid transaction is rolled back

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/f8a_jobs/scheduler.py", line 190, in job_execute
    instance.execute(**handler_kwargs)
  File "/usr/lib/python3.4/site-packages/f8a_jobs/handlers/selective_flow.py", line 17, in execute
    for args in self.expand_filter_query(node_args):
  File "/usr/lib/python3.4/site-packages/f8a_jobs/handlers/base.py", line 134, in expand_filter_query
    query_result = self.postgres.session.execute(select_statement).fetchall()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/orm/session.py", line 1107, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1121, in _execute_context
    None, None)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1114, in _execute_context
    conn = self._revalidate_connection()
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
    "Can't reconnect until invalid "
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: 'SELECT DISTINCT "packages"."name" AS "name", "ecosystems"."name" AS "ecosystem", "versions"."identifier" AS "version" FROM "worker_results" INNER JOIN "analyses" ON "worker_results"."analysis_id" = "analyses"."id" INNER JOIN "versions" ON "analyses"."version_id" = "versions"."id" INNER JOIN "packages" ON "versions"."package_id" = "packages"."id" INNER JOIN "ecosystems" ON "ecosystems"."id" = "packages"."ecosystem_id" WHERE "worker_results"."error" = FALSE AND "worker_results"."worker" = \'InitAnalysisFlow\''] [parameters: [{}]]
```

This issue was also spotted on worker with same exception type and message.

**Comment by fridex** [comment]
With https://github.com/fabric8-analytics/fabric8-analytics-worker/commit/4fc5315d1f94216bd2ecf9f7b0fd219c46ae64e4 we should be fine here. Hopefully apscheduler knows how to recover (I was not able to create issue with getting pgbouncer down). Closing this issue, feel free to reopen if this issue persists.

**Comment by jpopelka** [comment]
Reopenning, the issue strikes back.

**Comment by tisnik** [comment]
@fridex @jpopelka FYI: the 500 is returned yet again in the staging environment.
