### ISSUE TITLE
Bad Gateway for url: http://pypi-ranking.info/alltime?page=1

### ISSUE THREAD

**Issue by jpopelka** [fabric8-analytics/fabric8-analytics-jobs#117]
`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://localhost:34000/api/v1/jobs/analyses?state=running&popular=true&ecosystem=pypi&count=1&nversions=1&force=false&recursive_limit=0&force_graph_sync=false'`

```
coreapi-jobs            | ERROR:root:Job 'None' failed, registering ErrorHandler: 502 Server Error: Bad Gateway for url: http://pypi-ranking.info/alltime?page=1
coreapi-jobs            | Traceback (most recent call last):
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/f8a_jobs/scheduler.py", line 190, in job_execute
coreapi-jobs            |     instance.execute(**handler_kwargs)
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/f8a_jobs/handlers/base.py", line 274, in execute
coreapi-jobs            |     return self.do_execute(popular)
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/f8a_jobs/handlers/python_popular_analyses.py", line 96, in do_execute
coreapi-jobs            |     self._use_pypi_ranking()
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/f8a_jobs/handlers/python_popular_analyses.py", line 62, in _use_pypi_ranking
coreapi-jobs            |     pop.raise_for_status()
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/requests/models.py", line 937, in raise_for_status
coreapi-jobs            |     raise HTTPError(http_error_msg, response=self)
coreapi-jobs            | requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://pypi-ranking.info/alltime?page=1
```

**Comment by fridex** [comment]
It looks like http://pypi-ranking.info/ is down/overloaded now.

**Comment by jpopelka** [comment]
Seems it's not the first time:

- https://stackoverflow.com/questions/31117948/what-happened-to-pypi-package-ranking-website
- https://www.reddit.com/r/Python/comments/3bo3wc/what_happened_to_pypirankinginfo/

**Comment by jpopelka** [comment]
I've sent an email to owner asking for status.

**Comment by jpopelka** [comment]
> I've sent an email to owner asking for status.

no reply since then
