### ISSUE TITLE
Purge queues endpoint fails with NoRegionError

### ISSUE THREAD

**Issue by fridex** [fabric8-analytics/fabric8-analytics-jobs#188]
```

ERROR:root:Job 'None' failed, registering ErrorHandler: You must specify a region.
--
  | Traceback (most recent call last):
  | File "/usr/lib/python3.4/site-packages/f8a_jobs/scheduler.py", line 243, in job_execute
  | instance.execute(**handler_kwargs)
  | File "/usr/lib/python3.4/site-packages/f8a_jobs/handlers/sqs_purge.py", line 24, in execute
  | aws_secret_access_key=aws_secret_access_key)
  | File "/usr/lib/python3.4/site-packages/boto3/__init__.py", line 83, in client
  | return _get_default_session().client(*args, **kwargs)
  | File "/usr/lib/python3.4/site-packages/boto3/session.py", line 263, in client
  | aws_session_token=aws_session_token, config=config)
  | File "/usr/lib/python3.4/site-packages/botocore/session.py", line 836, in create_client
  | client_config=config, api_version=api_version)
  | File "/usr/lib/python3.4/site-packages/botocore/client.py", line 71, in create_client
  | verify, credentials, scoped_config, client_config, endpoint_bridge)
  | File "/usr/lib/python3.4/site-packages/botocore/client.py", line 281, in _get_client_args
  | verify, credentials, scoped_config, client_config, endpoint_bridge)
  | File "/usr/lib/python3.4/site-packages/botocore/args.py", line 45, in get_client_args
  | endpoint_url, is_secure, scoped_config)
  | File "/usr/lib/python3.4/site-packages/botocore/args.py", line 111, in compute_client_args
  | service_name, region_name, endpoint_url, is_secure)
  | File "/usr/lib/python3.4/site-packages/botocore/client.py", line 354, in resolve
  | service_name, region_name)
  | File "/usr/lib/python3.4/site-packages/botocore/regions.py", line 122, in construct_endpoint
  | partition, service_name, region_name)
  | File "/usr/lib/python3.4/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
  | raise NoRegionError()
  | botocore.exceptions.NoRegionError: You must specify a region.


```

**Comment by fridex** [comment]
CC @msrb
