### ISSUE TITLE
Unable to make any API calls due to authorization failure

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-jobs#244]
I have encountered the following error multiple times, due to which we cannot invoke any Jobs APIs:

```
[Sun Jan 28 10:58:41 2018] GET /api/v1/generate-token => generated 699 bytes in 2 msecs (HTTP/1.1 302) 4 headers in 540 bytes (1 switches on core 0)
2018-01-28 10:58:42,689 - Authorized redirection triggered, getting authorized response from Github
INFO:f8a_jobs.api_v1:Authorized redirection triggered, getting authorized response from Github
2018-01-28 10:58:42,761 - Got Github authorized response
INFO:f8a_jobs.api_v1:Got Github authorized response
2018-01-28 10:58:42,761 - Assigning authorization token '********' to session
DEBUG:f8a_jobs.api_v1:Assigning authorization token '********' to session
[2018-01-28 10:58:42,896] ERROR in app: Exception on /api/v1/authorized [GET]
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.4/site-packages/connexion/decorators/decorator.py", line 118, in wrapper
    response_container = function(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/connexion/decorators/produces.py", line 100, in wrapper
    response = function(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/connexion/decorators/decorator.py", line 98, in wrapper
    operation_handler_result = function(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/connexion/decorators/parameter.py", line 161, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/f8a_jobs/api_v1.py", line 78, in authorized
    if not is_organization_member(oauth_info.data):
  File "/usr/lib/python3.4/site-packages/f8a_jobs/utils.py", line 117, in is_organization_member
    data.raise_for_status()
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/users/********/orgs?access_token=********
```

We have to generate an OAuth2 token in order to authorize the API requests to Jobs service. This is done using `/generate-token` API. As shown in the error above, we are successfully able to obtain the token. However in the subsequent to calls (via redirect) to `/authorized` the authentication fails.

**Comment by tuxdna** [comment]
Related PRs to fix this haven't worked so far:

 * https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/242
 * https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/243

**Comment by tuxdna** [comment]
@msrb: PTAL - https://github.com/fabric8-analytics/fabric8-analytics-jobs/pull/245 :-)

**Comment by msrb** [comment]
Note previous PRs were addressing the "unknown token" issue. This issue is different.

Thanks for fixing it @tuxdna 😉
