### ISSUE TITLE
KeyError: 'SENTRY_DSN'

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-jobs#261]
With latest images, and doing `./docker-compose.sh up` I see this error:

```
coreapi-jobs            | Traceback (most recent call last):
coreapi-jobs            |   File "/usr/bin/f8a-jobs.py", line 68, in <module>
coreapi-jobs            |     init_selinon()
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/f8a_worker/setup_celery.py", line 49, in init_selinon
coreapi-jobs            |     Config.set_config_yaml(nodes_config, flows_config)
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/selinon/config.py", line 140, in set_config_yaml
coreapi-jobs            |     system = System.from_files(nodes_definition_file, flow_definition_files)
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/selinon/system.py", line 1159, in from_files
coreapi-jobs            |     cls._setup_nodes(system, nodes_definition, nodes_definition_file)
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/selinon/system.py", line 1074, in _setup_nodes
coreapi-jobs            |     GlobalConfig.from_dict(system, nodes_definition['global'])
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/selinon/global_config.py", line 198, in from_dict
coreapi-jobs            |     cls._parse_trace(system, dict_.pop('trace'))
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/selinon/global_config.py", line 182, in _parse_trace
coreapi-jobs            |     cls._parse_trace_sentry(entry['sentry'])
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/selinon/global_config.py", line 138, in _parse_trace_sentry
coreapi-jobs            |     dsn = dsn.format(**os.environ)
coreapi-jobs            | KeyError: 'SENTRY_DSN'

```

**Comment by fridex** [comment]
This shouldn't be fatal. Feel free to report issue on Selinon upstream issue tracker.

**Comment by fridex** [comment]
> This shouldn't be fatal. Feel free to report an issue on Selinon upstream issue tracker.

Agh, this is during initialization - in that case adjust your docker-compose.

**Comment by tuxdna** [comment]
@fridex: Yes this is a config issue.
