### ISSUE TITLE
Jobs docker image raises exception with latest images

### ISSUE THREAD

**Issue by tuxdna** [fabric8-analytics/fabric8-analytics-jobs#280]
Local setup is giving following errors with latest Docker images:

```
coreapi-jobs            | + f8a-jobs.py initjobs
coreapi-jobs            | Traceback (most recent call last):
coreapi-jobs            |   File "/usr/bin/f8a-jobs.py", line 11, in <module>
coreapi-jobs            |     from f8a_jobs.scheduler import Scheduler
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/f8a_jobs/scheduler.py", line 20, in <module>
coreapi-jobs            |     import f8a_jobs.handlers as handlers
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/f8a_jobs/handlers/__init__.py", line 17, in <module>
coreapi-jobs            |     from .nuget_popular_analyses import NugetPopularAnalyses
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/f8a_jobs/handlers/nuget_popular_analyses.py", line 8, in <module>
coreapi-jobs            |     from f8a_worker.solver import NugetReleasesFetcher
coreapi-jobs            |   File "/usr/lib/python3.4/site-packages/f8a_worker/solver.py", line 10, in <module>
coreapi-jobs            |     from pip._internal.req.req_file import parse_requirements
coreapi-jobs            | ImportError: No module named 'pip._internal'

```

Due to above error I am not able to run ingestion on my system.

Apparently, many others are facing same issue with latest pip3 recently:

 - https://github.com/pypa/pip/issues/5253
 - https://askubuntu.com/questions/1025189/pip-is-not-working-importerror-no-module-named-pip-internal

For:

 * https://github.com/fabric8-analytics/fabric8-analytics-jobs/issues/280

**Comment by tuxdna** [comment]
Jobs image uses older version of worker base image, hence the error. Need to bump worker version in Docker file.
