### ISSUE TITLE
[maven-indexer] java.io.IOException: No space left on device

### ISSUE THREAD

**Issue by msrb** [fabric8-analytics/fabric8-analytics-jobs#39]
Updating maven index seems to be an impossible task.

```
[main] INFO com.redhat.maven.index.checker.MavenIndexChecker -   Downloading nexus-maven-repository-index.439.gz
[main] INFO com.redhat.maven.index.checker.MavenIndexChecker -  - Done
Exception in thread "main" java.io.IOException: No space left on device
	at java.io.RandomAccessFile.writeBytes(Native Method)
	at java.io.RandomAccessFile.write(RandomAccessFile.java:525)
	at org.apache.lucene.store.FSDirectory$FSIndexOutput.flushBuffer(FSDirectory.java:403)
	at org.apache.lucene.store.BufferedIndexOutput.writeBytes(BufferedIndexOutput.java:81)
	at org.apache.lucene.store.CompoundFileWriter$DirectCFSIndexOutput.writeBytes(CompoundFileWriter.java:365)
	at org.apache.lucene.store.DataOutput.copyBytes(DataOutput.java:255)
	at org.apache.lucene.store.Directory.copy(Directory.java:195)
	at org.apache.lucene.store.TrackingDirectoryWrapper.copy(TrackingDirectoryWrapper.java:50)
	at org.apache.lucene.index.IndexWriter.createCompoundFile(IndexWriter.java:4657)
	at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:535)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:502)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:518)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:628)
	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2937)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3096)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3063)
	at org.apache.maven.index.updater.IndexDataReader.readIndex(IndexDataReader.java:99)
	at org.apache.maven.index.updater.DefaultIndexUpdater.unpackIndexData(DefaultIndexUpdater.java:424)
	at org.apache.maven.index.updater.DefaultIndexUpdater.loadIndexDirectory(DefaultIndexUpdater.java:215)
	at org.apache.maven.index.updater.DefaultIndexUpdater.access$300(DefaultIndexUpdater.java:87)
	at org.apache.maven.index.updater.DefaultIndexUpdater$LuceneIndexAdaptor.addIndexChunk(DefaultIndexUpdater.java:551)
	at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:746)
	at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:171)
	at com.redhat.maven.index.checker.MavenIndexChecker.perform(MavenIndexChecker.java:235)
	at com.redhat.maven.index.checker.MavenIndexChecker.main(MavenIndexChecker.java:111)
command ['java', '-Xmx768m', '-jar', 'maven-index-checker.jar', '-r', '380000-390000'] ended with 1

exception is fatal
ERROR:root:Job 'None' failed, registering ErrorHandler: Error during running command ['java', '-Xmx768m', '-jar', 'maven-index-checker.jar', '-r', '380000-390000']: ''
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/cucoslib/utils.py", line 261, in get_command_output
    out = check_output(args, universal_newlines=True, **kwargs)
  File "/usr/lib64/python3.4/subprocess.py", line 617, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['java', '-Xmx768m', '-jar', 'maven-index-checker.jar', '-r', '380000-390000']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/f8a_jobs/scheduler.py", line 190, in job_execute
    instance.execute(**handler_kwargs)
  File "/usr/lib/python3.4/site-packages/f8a_jobs/handlers/base.py", line 264, in execute
    return self.do_execute(popular)
  File "/usr/lib/python3.4/site-packages/f8a_jobs/handlers/maven_popular_analyses.py", line 156, in do_execute
    self._use_maven_index_checker()
  File "/usr/lib/python3.4/site-packages/f8a_jobs/handlers/maven_popular_analyses.py", line 126, in _use_maven_index_checker
    output = TimedCommand.get_command_output(command, is_json=True, graceful=False, timeout=1200)
  File "/usr/lib/python3.4/site-packages/cucoslib/utils.py", line 245, in get_command_output
    return get_command_output(args, graceful, is_json, **kwargs)
  File "/usr/lib/python3.4/site-packages/cucoslib/utils.py", line 271, in get_command_output
    raise TaskError("Error during running command %s: %r" % (args, ex.output))
cucoslib.errors.TaskError: Error during running command ['java', '-Xmx768m', '-jar', 'maven-index-checker.jar', '-r', '380000-390000']: ''
```

**Comment by jpopelka** [comment]
https://github.com/openshiftio/openshift.io/issues/1298
